#logging.level.org.springframework.web=DEBUG
#spring.jpa.open-in-view=false
#spring.h2.console.enabled=true
#
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
    port: 8080
    servlet:
        context-path: /
        encoding:
            charset: UTF-8
            enabled: true
            force: true
spring:
    jpa:
        open-in-view: true
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                show_sql: false
                format_sql: true
                highlight_sql: true
    datasource:
        url: jdbc:postgresql://db.fwsspudyollydfupfjne.supabase.co:5432/postgres
        username: postgres
        password: sb2005@sb2005
logging:
    pattern:
        console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
    level:
        org:
            hibernate:
            SQL: debug
            type.descriptor.sql: trace
jwt:
    secret: DadFufN4Oui8Bfv3ScFj6R9fyJ9hD45E6AGFsXgFsRhT4YSdSb
